# Portal profile to manage the OpenBar client

name = "OpenBar"

[[fs.bind]]
path = "/bin"

[[fs.bind]]
path = "/etc"

[[fs.bind]]
path = "/lib"

[[fs.bind]]
path = "/lib64"

[[fs.bind]]
path = "/usr"

[[fs.bind]]
path = "/var/cache"

[[fs.bind]]
path = "/home/user/Clients/OpenBar"
write = true

[run]
cmd = ["/bin/sh"]
