[project]
name = "stemjail"
version = "0.0.1"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]

[lib]
name = "stemjail"
path = "src/stemjail/mod.rs"

[dependencies]
bitflags = "*"
env_logger = "*"
getopts = "*"
log = "*"
rand = "*"
rustc-serialize = "*"
toml = "*"

[dependencies.iohandle]
path = "../iohandle-rs"
version = ">= 0.1.0"

[dependencies.mnt]
path = "../mnt-rs"
version = ">= 0.2.0"

[dependencies.pty]
path = "../pty-rs"
version = ">= 0.1.0"
