[project]
name = "stemjail"
version = "0.0.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]

[[bin]]
name = "kage"
path = "src/kage.rs"

[[bin]]
name = "portal"
path = "src/portal.rs"

[lib]
name = "stemjail"
path = "src/stemjail/mod.rs"

[dependencies.toml]
path = "../toml-rs"
