[package]
name = "stemjail"
version = "0.2.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]
description = "Dynamic user-activity isolation"
repository = "https://github.com/stemjail/stemjail"
readme = "README.md"
keywords = ["security", "linux", "ACL", "sandbox"]
license = "LGPL-3.0"
exclude = [".gitignore"]

[dependencies]
bitflags = "*"
env_logger = "*"
getopts = "*"
log = "*"
rand = "*"
rustc-serialize = "*"
toml = "*"

[dependencies.mnt]
path = "../mnt-rs"
version = ">= 0.2.0"

[dependencies.pty]
path = "../pty-rs"
version = ">= 0.1.0"

[dependencies.stemflow]
path = "../stemflow"
version = ">= 0.5.0"
