[project]
name = "stemjail"
version = "0.0.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]

[[bin]]
name = "kage"
path = "src/kage.rs"

[[bin]]
name = "portal"
path = "src/portal.rs"

[lib]
name = "stemjail"
path = "src/stemjail/mod.rs"

[dependencies.iohandle]
path = "../iohandle-rs"

[dependencies.mnt]
path = "../mnt-rs"

[dependencies.pty]
path = "../pty-rs"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs.git"
rev = "4bb575fdaf5fd88580abbac6fdb057ef76d32251"
