# Portal profile example #1

name = "example1"

[socket]
path = "./portal.sock"

[fs]
root = "./tmp-chroot"

[[fs.bind]]
src = "/tmp"
write = true

[[fs.bind]]
src = "/home"
dst = "/data-ro"

[run]
cmd = ["/bin/sh", "-c", "id"]
